### ISSUE TITLE
[#275] App freezes using a specific css code

### ISSUE THREAD

**Issue by Su-Yong** [organization/alspotron#288]
# 현재까지 알려진 정보
- 특정 CSS코드에서만 발생하는 문제이다
- ~~특정 css declaration이 문제이다~~ -> 문제가 생기지 않는 [CSS](https://github.com/organization/alspotron/blob/master/example/custom-css.css)와 동일한 declaration만 사용해도 문제가 생김
- [해당부분](https://github.com/organization/alspotron/blob/693b9c2c5017dc8580c2ab5a3d9921aaa63fae96/renderer/main/App.tsx#L94-L123)의 `style`시그널을 가져오는 곳에서 문제가 일어난다
- Main Thread가 죽는다
- Windows 11에서 발생한다 + MacOS에서도 동일한 현상 발생
- 가끔 자동생성된 기본 테마를 사용하면 교체가 정상적으로 된다
- `style` 시그널의 Owner를 강제로 `renderer/main/App.tsx`로 설정하면 정상적으로 동작한다. (단 시그널이 정상적으로 subscribe되지않음)
- ~~`CSSStyleSheet.replace` -> `CSSStyleSheet.replaceSync`로 바꾸면 동작한다~~ -> 컴퓨터를 재부팅한 이후 다시 시도해보니 동작하지 않음
- ~~특정 electron 버전이 문제이다~~ -> 이전 electron버전을 사용해도 동일한 증상 발생
- ~~CSSStyleSheet를 adoptedStyleSheet로 추가한것이 문제이다~~ -> style element를 append해도 동일한 증상 발생
- `Stylis` 문제인것으로 추정됨

# Notes
- 문제가 생기는 css
```css
alspotron-wrapper {
  padding-bottom: 10px;
  padding-right: 10px;

  /* for overwatch */
  transform: skew(0, 4deg) translateY(-14px);
}

alspotron-lyrics-item {
  background: transparent !important;
  text-shadow: 2px 2px 10px black;
  filter: none !important;
}

alspotron-transition-lyric-enter-active,
alspotron-transition-lyric-exit-active {
  transition: all 1s cubic-bezier(0.68, -0.6, 0.32, 1.6);
  transform-origin: center;
}

alspotron-transition-lyric-move {
  transition: all 1s cubic-bezier(0.68, -0.6, 0.32, 1.6);
  transform-origin: center;
}

alspotron-transition-lyric-enter,
alspotron-transition-lyric-exit-to {
  opacity: 0 !important;
}

alspotron-nowplaying {
  width: 150px;
  height: 150px;

  position: relative;
  filter: opacity(0.5);

  border-radius: 16px;
  display: flex;
  flex-direction: column;
  justify-content: end;
  align-items: stretch;
  padding: 0;
  box-shadow: 0 0 10px 0 rgba(0, 0, 0, .3);
}

alspotron-nowplaying-cover {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;

  &--disabled {
    scale: 105% !important;
  }
}

alspotron-nowplaying-marquee {
  position: relative;

  width: 100%;
  height: 100%;

  background: linear-gradient(to bottom, rgba(0, 0, 0, 0) 0%, black 100%);
  backdrop-filter: blur(1px);
}

alspotron-nowplaying-playing-text {
  height: 100%;

  display: flex;
  flex-direction: column;
  align-items: flex-start;

  padding: 0 16px 16px;
}

alspotron-nowplaying-title {
  font-size: 1.2rem;
}

alspotron-nowplaying-artist {
  opacity: 0.3;
  order: 2;
  margin-top: -7px;
  font-size: 0.9rem;
}

alspotron-nowplaying-divider {
  display: none;
}

alspotron-nowplaying-progress-bar {
  position: absolute;
  width: 100%;
  height: 100%;
  border-radius: 16px;

  z-index: 100;
  box-shadow: 0 0 0 4px rgb(6 182 212 / 0.5) inset;
  clip-path: path("M0.5 1 A1.5 1.5 0 1 0 0 0.5");

  &::before,
  &::after {
    font-size: 0.8rem;
    opacity: 0.3;
  }

  &::before {
    position: absolute;
    right: 0;
    bottom: 0;
    content: var(--nowplaying-duration);
    padding-right: 5px;
  }

  &::after {
    position: absolute;
    bottom: 0;
    content: var(--nowplaying-progress);
  }
}

alspotron-nowplaying-progress {
  position: relative;
  background: rgba(255, 255, 255, .3) !important;
  border-radius: 3px;
  height: 4px;

  transform: none;
  flex: 1;

  &::before {
    content: '';
    position: absolute;
    inset: 0;
    width: 100%;
    background: white !important;
    transform: scaleX(var(--percent));
    transform-origin: left;
  }
}
```
